/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zkteco_id100com_jni_id100sdk */

#ifndef _Included_zkteco_id100com_jni_id100sdk
#define _Included_zkteco_id100com_jni_id100sdk
//#ifdef __cplusplus
//extern "C" {
//#endif
/*
 * Class:     zkteco_id100com_jni_id100sdk
 * Method:    InitComm
 * Signature: (I)I
 */
/*JNIEXPORT*/ jint JNICALL Java_zkteco_id100com_jni_id100sdk_InitComm
  (JNIEnv *, jclass, jint);

/*
 * Class:     zkteco_id100com_jni_id100sdk
 * Method:    InitCommExt
 * Signature: ()I
 */
/*JNIEXPORT*/ jint JNICALL Java_zkteco_id100com_jni_id100sdk_InitCommExt
  (JNIEnv *, jclass);

/*
 * Class:     zkteco_id100com_jni_id100sdk
 * Method:    CloseComm
 * Signature: ()I
 */
/*JNIEXPORT*/ jint JNICALL Java_zkteco_id100com_jni_id100sdk_CloseComm
  (JNIEnv *, jclass);

/*
 * Class:     zkteco_id100com_jni_id100sdk
 * Method:    Authenticate
 * Signature: ()I
 */
/*JNIEXPORT*/ jint JNICALL Java_zkteco_id100com_jni_id100sdk_Authenticate
  (JNIEnv *, jclass);

/*
 * Class:     zkteco_id100com_jni_id100sdk
 * Method:    Read_Content
 * Signature: (I)I
 */
/*JNIEXPORT*/ jint JNICALL Java_zkteco_id100com_jni_id100sdk_Read_Content
  (JNIEnv *, jclass, jint);

/*
 * Class:     zkteco_id100com_jni_id100sdk
 * Method:    Read_Content
 * Signature: (I)I
 */
/*JNIEXPORT*/ jint JNICALL Java_zkteco_id100com_jni_id100sdk_ReadContent
  (JNIEnv *, jclass, jint);

/*
 * Class:     zkteco_id100com_jni_id100sdk
 * Method:    GetSAMID
 * Signature: ([Ljava/lang/Byte;)I
 */
/*JNIEXPORT*/ jint JNICALL Java_zkteco_id100com_jni_id100sdk_GetSAMID
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     zkteco_id100com_jni_id100sdk
 * Method:    GetBmpPhoto
 * Signature: (Ljava/lang/String;)I
 */
/*JNIEXPORT*/ jint JNICALL Java_zkteco_id100com_jni_id100sdk_GetBmpPhoto
  (JNIEnv *, jclass, jstring);

 /*
 * Class:     zkteco_id100com_jni_id100sdk
 * Method:    Reset_SAM
 * Signature: ()I
 */
/*JNIEXPORT*/ jint JNICALL Java_zkteco_id100com_jni_id100sdk_ResetSAM
  (JNIEnv *, jclass);

 /*
 * Class:     zkteco_id100com_jni_id100sdk
 * Method:    GetSAMStatus
 * Signature: ()I
 */
/*JNIEXPORT*/ jint JNICALL Java_zkteco_id100com_jni_id100sdk_GetSAMStatus
  (JNIEnv *, jclass);


//#ifdef __cplusplus
//}
//#endif
#endif
